const colors = {
  // Overboard North Nautical Brand
  charcoalNavy: '#2B3440',
  mutedTeal: '#4C7D7C',
  sunsetCoral: '#EE6E56',
  warmSand: '#FEFEFE',
  driftwoodGray: '#6A6F73',
  
  // Legacy colors for gradual migration
  cream: '#FFF8F0',
  warmWhite: '#FEFEFE',
  terracotta: '#E07A5F',
  terracottaDark: '#C4684D',
  sage: '#81B29A',
  sageDark: '#6A9580',
  charcoal: '#2D3142',
  softGray: '#F4F4F4',
  mediumGray: '#9CA3AF',
  darkGray: '#4A4A4A',
  coral: '#F29F5A',
  coralLight: '#F5B985',
  mustard: '#F4B860',
  white: '#FFFFFF',
  black: '#000000',
  nauticalBlue: '#1D3C45',
  seafoamTeal: '#64B5C1',
  driftwoodBeige: '#C2B59B',
  creamSand: '#F4EFE6',
  mutedOrange: '#F29F5A',
  teal: '#64B5C1',
  tealDark: '#1D3C45',
  tealLight: '#8CCAD5',
  sand: '#C2B59B',
  sandLight: '#F4EFE6',
  driftwood: '#A89B8A',
  oceanDeep: '#1D3C45',
  oceanFoam: '#B3D4DB',
};

export default {
  light: {
    text: colors.charcoalNavy,
    background: colors.white,
    tint: colors.sunsetCoral,
    tabIconDefault: colors.driftwoodGray,
    tabIconSelected: colors.sunsetCoral,
    card: colors.white,
    border: colors.driftwoodGray,
    muted: colors.driftwoodGray,
    accent: colors.mutedTeal,
    accentLight: '#A3BEC0',
    cream: colors.warmSand,
    softGray: '#F5F5F7',
    charcoal: colors.charcoalNavy,
    mediumGray: colors.driftwoodGray,
    darkGray: colors.charcoalNavy,
    
    // Overboard North brand colors
    charcoalNavy: colors.charcoalNavy,
    mutedTeal: colors.mutedTeal,
    sunsetCoral: colors.sunsetCoral,
    warmSand: colors.warmSand,
    driftwoodGray: colors.driftwoodGray,
    
    // Legacy terracotta/sage for backward compatibility
    terracotta: colors.sunsetCoral,
    terracottaDark: '#D25E48',
    sage: colors.mutedTeal,
    sageLight: '#A3BEC0',
  },
  nautical: {
    blue: colors.charcoalNavy,
    seafoamTeal: colors.mutedTeal,
    driftwoodBeige: colors.driftwoodGray,
    creamSand: colors.warmSand,
    mutedOrange: colors.sunsetCoral,
    mustard: colors.sunsetCoral,
    teal: colors.mutedTeal,
    tealDark: colors.charcoalNavy,
    tealLight: '#7FA6A5',
    sand: colors.warmSand,
    sandLight: colors.warmSand,
    driftwood: colors.driftwoodGray,
    oceanDeep: colors.charcoalNavy,
    oceanFoam: '#A3C5C4',
  },
  white: colors.white,
  
  primary: colors.sunsetCoral,
  secondary: colors.mutedTeal,
  background: colors.warmSand,
  text: colors.charcoalNavy,
  textLight: colors.driftwoodGray,
  border: '#e5e7eb',
  neutralGray: '#9ca3af',
  success: '#10b981',
  warning: '#f59e0b',
  error: '#ef4444',
};
